### ISSUE TITLE
关于Deep3DFaceRecon 输出请教一个问题

### ISSUE THREAD

**Issue by zhanghongyong123456** [ykk648/face_power#2]
1. 经过Deep3D得到输出结果，如何获取人脸下半部分的 对应mask，如下图所示：
2![image](https://github.com/user-attachments/assets/07b0b7a3-3e68-436c-b389-4b4addd80ee5)

**Comment by ykk648** [comment]
不知你贴的哪篇论文，有lmk就有mask。

https://github.com/ykk648/face_power/blob/a09b505be14d188e3850eca5f82bd4c410bc26a4/face_3d/Deep3DFaceRecon/face_3d_coeffs.py#L49
